export const modules = [
  {
    num: 1,
    title: 'What Is AI Bias?',
    subtitle: 'Technical Foundations',
    cs: false,
    desc: 'Define AI bias. Distinguish historical, representation, measurement, and amplification bias. Trace the feedback loop that turns biased data into biased futures.',
    tags: ['Historical Bias', 'Representation', 'Amplification'],
    headerMeta: 'Module 01 · No CS Required · 90 min',
    headerColor: 'var(--accent)',
  },
  {
    num: 2,
    title: 'AI Bias in Healthcare',
    subtitle: null,
    cs: false,
    desc: 'How a single proxy variable denied Black patients appropriate care — in 200 million cases. Plus: Claude, ChatGPT, Gemini all tested for psychiatric treatment bias.',
    tags: ['Clinical AI', 'Racial Bias', 'Healthcare Equity'],
    headerMeta: 'Module 02 · No CS Required · 90 min',
    headerColor: 'var(--accent)',
  },
  {
    num: 3,
    title: 'AI Bias in Hiring',
    subtitle: null,
    cs: false,
    desc: "AI screeners favored white-associated names 85% of the time. And humans couldn't correct the bias even when warned. Then there's Mobley v. Workday.",
    tags: ['Resume Screening', 'Legal Cases', 'Discrimination'],
    headerMeta: 'Module 03 · No CS Required · 90 min',
    headerColor: 'var(--accent)',
  },
  {
    num: 4,
    title: 'AI Bias in Financial Advice',
    subtitle: null,
    cs: false,
    desc: 'Conservative advice compounds into lower wealth. Vulnerable users get worse info. Live activity: test an AI chatbot with identical questions from different names.',
    tags: ['Gender Bias', 'Fintech', 'Wealth Inequality'],
    headerMeta: 'Module 04 · No CS Required · Fintech Club Workshop · 90 min',
    headerColor: 'var(--accent)',
  },
  {
    num: 5,
    title: 'Facial Recognition & Predictive Policing',
    subtitle: null,
    cs: true,
    desc: '34.7% error rate for darker-skinned women vs 1% for lighter-skinned men. In nearly every documented wrongful arrest from facial recognition, the person was Black.',
    tags: ['Civil Liberties', 'Feedback Loops', 'Policing'],
    headerMeta: 'Module 05 · CS Recommended · 90 min',
    headerColor: 'var(--accent2)',
  },
  {
    num: 6,
    title: 'AI Bias in Social Media Algorithms',
    subtitle: null,
    cs: true,
    desc: 'Llama 2 described women in domestic work roles 4× more often than men (UNESCO, 2024). AI image generators almost exclusively depict scientists as white and male. Audit your own feed.',
    tags: ['Recommendation Algorithms', 'Content Moderation'],
    headerMeta: 'Module 06 · CS Recommended · 90 min',
    headerColor: 'var(--accent2)',
  },
  {
    num: 7,
    title: 'Policy, Regulation & Advocacy',
    subtitle: null,
    cs: true,
    desc: 'Colorado SB 24-205. The EU AI Act. EEOC guidance. Draft a real AI bias policy for a school, hospital, city, or bank. Then defend it.',
    tags: ['Legislation', 'EU AI Act', 'Advocacy'],
    headerMeta: 'Module 07 · CS Recommended · 90 min',
    headerColor: 'var(--accent2)',
  },
  {
    num: 8,
    title: 'How to Build Fairer AI',
    subtitle: null,
    cs: true,
    desc: 'Dataset interventions, fairness constraints, RLHF reward debiasing (the GUARD paper), post-hoc auditing. Then: why 42% of AI companies deploy biased systems anyway.',
    tags: ['RLHF', 'Fairness Metrics', 'GUARD'],
    headerMeta: 'Module 08 · CS Recommended · 90 min',
    headerColor: 'var(--accent2)',
  },
];

export const bibGroups = [
  {
    title: 'Modules 1 & 2 — Foundations and Healthcare',
    entries: [
      { text: 'Obermeyer Z, Powers B, Vogeli C, Mullainathan S. (2019). Dissecting racial bias in an algorithm used to manage the health of populations. Science, 366(6464), 447–453.', url: 'https://pubmed.ncbi.nlm.nih.gov/31649194/', urlLabel: 'pubmed.ncbi.nlm.nih.gov/31649194' },
      { text: 'Cross JL, Choma MA, Onofrey JA. (2024). Bias in medical AI: Implications for clinical decision-making. PLOS Digital Health, 3(11): e0000651.', url: 'https://doi.org/10.1371/journal.pdig.0000651', urlLabel: 'doi.org/10.1371/journal.pdig.0000651' },
      { text: 'Glickman M, Sharot T. (2024). How human-AI feedback loops alter human perceptual, emotional and social judgements. Nature Human Behaviour.', url: 'https://www.ucl.ac.uk/news/2024/dec/bias-ai-amplifies-our-own-biases', urlLabel: 'UCL News coverage' },
      { text: 'Guilbeault D, Delecourt S, Desikan BS. (October 8, 2025). Age and gender distortion in online media and large language models. Nature, 646, 1129–1137.', url: 'https://www.nature.com/articles/s41586-025-09581-z', urlLabel: 'nature.com' },
      { text: 'Bouguettaya A, Stuart EM, Aboujaoude E. (June 4, 2025). Racial bias in AI-mediated psychiatric diagnosis and treatment: a qualitative comparison of four large language models. npj Digital Medicine, 8:332.', url: 'https://pubmed.ncbi.nlm.nih.gov/40467886/', urlLabel: 'pubmed.ncbi.nlm.nih.gov/40467886' },
      { text: 'Buolamwini J, Gebru T. (2018). Gender Shades: Intersectional Accuracy Disparities in Commercial Gender Classification. PMLR, 81:77–91.', url: 'https://proceedings.mlr.press/v81/buolamwini18a.html', urlLabel: 'proceedings.mlr.press' },
    ],
  },
  {
    title: 'Module 3 — Hiring',
    entries: [
      { text: 'University of Washington. (October 31, 2024). AI bias in resume screening: race and gender.', url: 'https://www.washington.edu/news/2024/10/31/ai-bias-resume-screening-race-gender/', urlLabel: 'washington.edu' },
      { text: 'University of Washington. (November 10, 2025). People mirror AI systems\' hiring biases, study finds.', url: 'https://www.washington.edu/news/2025/11/10/people-mirror-ai-systems-hiring-biases-study-finds/', urlLabel: 'washington.edu' },
      { text: 'FairNow. (November 27, 2025). Workday lawsuit over AI hiring bias.', url: 'https://fairnow.ai/workday-lawsuit-resume-screening/', urlLabel: 'fairnow.ai' },
      { text: 'Holland & Knight. (May 2025). Federal court allows collective action lawsuit over alleged AI hiring bias.', url: 'https://www.hklaw.com/en/insights/publications/2025/05/federal-court-allows-collective-action-lawsuit-over-alleged', urlLabel: 'hklaw.com' },
      { text: 'Clark Hill. (2025). From algorithms to deepfakes: AI risks every employer must confront.', url: 'https://www.clarkhill.com/news-events/news/from-algorithms-to-deepfakes-ai-risks-every-employer-must-confront/', urlLabel: 'clarkhill.com' },
    ],
  },
  {
    title: 'Module 4 — Financial Advice',
    entries: [
      { text: 'SSRN. (2024). AI financial advice and gender bias.', url: 'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4880335', urlLabel: 'ssrn.com' },
      { text: 'MIT News. (February 19, 2026). Study: AI chatbots provide less accurate information to vulnerable users.', url: 'https://news.mit.edu/2026/study-ai-chatbots-provide-less-accurate-information-vulnerable-users-0219', urlLabel: 'news.mit.edu' },
      { text: 'Robert & Ethel Kennedy Human Rights Center. (August 2025). Bias in code: Algorithm discrimination in financial systems.', url: 'https://rfkhumanrights.org/our-voices/bias-in-code-algorithm-discrimination-in-financial-systems/', urlLabel: 'rfkhumanrights.org' },
      { text: 'Morrison Foerster. (January 27, 2026). AI and algorithmic bias in financial services.', url: 'https://www.mofo.com/resources/insights/260127-ai-trends-for-2026-ai-and-algorithmic-bias', urlLabel: 'mofo.com' },
    ],
  },
  {
    title: 'Module 5 — Policing',
    entries: [
      { text: 'Stateline. (February 4, 2025). Facial recognition in policing is getting state-by-state guardrails.', url: 'https://stateline.org/2025/02/04/facial-recognition-in-policing-is-getting-state-by-state-guardrails/', urlLabel: 'stateline.org' },
      { text: 'Washington Post. (January 13, 2025). Arrested by AI: Police ignore standards after facial recognition matches.', url: 'https://www.washingtonpost.com/business/interactive/2025/police-artificial-intelligence-facial-recognition/', urlLabel: 'washingtonpost.com' },
      { text: 'ACLU. Williams v. City of Detroit.', url: 'https://www.aclu.org/cases/williams-v-city-of-detroit-face-recognition-false-arrest', urlLabel: 'aclu.org' },
    ],
  },
  {
    title: 'Module 6 — Social Media',
    entries: [
      { text: 'UNESCO. (2024). Bias Against Women and Girls in Large Language Models. Finds that Llama 2 described women in domestic work roles four times more often than men.', url: 'https://www.unesco.org/en/articles/generative-ai-unesco-study-reveals-alarming-evidence-regressive-gender-stereotypes', urlLabel: 'unesco.org' },
      { text: 'Gorska et al. (November 14, 2025). Algorithmic bias in image-generating AI: prevalence and user perceptions. Information, Communication & Society.', url: 'https://www.tandfonline.com/doi/full/10.1080/1369118X.2025.2584146', urlLabel: 'tandfonline.com' },
      { text: 'Frontiers in Communication. (January 8, 2025). Algorithmic agency and discriminatory Instagram content moderation.', url: 'https://www.frontiersin.org/journals/communication/articles/10.3389/fcomm.2024.1385869/full', urlLabel: 'frontiersin.org' },
    ],
  },
  {
    title: 'Module 7 — Policy',
    entries: [
      { text: 'U.S. Commission on Civil Rights. (2024). Rising use of artificial intelligence in K–12 education.', url: 'https://www.usccr.gov/reports/2024/rising-use-artificial-intelligence-k-12-education', urlLabel: 'usccr.gov' },
    ],
  },
  {
    title: 'Module 8 — Building Fairer AI',
    entries: [
      { text: 'IBM. (January 2024). Global AI Adoption Index 2023. Reports that only 27% of AI-deploying organizations are taking active steps to reduce algorithmic bias.', url: 'https://newsroom.ibm.com/2024-01-10-Data-Suggests-Growth-in-Enterprise-Adoption-of-AI-is-Due-to-Widespread-Deployment-by-Early-Adopters', urlLabel: 'newsroom.ibm.com' },
      { text: 'Bhattacharya D et al. (2024). GUARD: Guiding Unbiased Alignment through Reward Debiasing. Accepted to EMNLP; presented at NeurIPS workshops.' },
      { text: 'Haghighi N, Landay J et al. (April 2025). Ontological bias in LLMs. CHI 2025. Reported by Stanford HAI (July 2025).', url: 'https://hai.stanford.edu/news/when-ai-imagines-a-tree-how-your-chatbots-worldview-shapes-your-thinking', urlLabel: 'hai.stanford.edu' },
      { text: 'Laurito W et al. (July 2025). AI-AI bias: Large language models favor communications generated by large language models. PNAS, 122(31) e2415697122.', url: 'https://www.pnas.org/doi/10.1073/pnas.2415697122', urlLabel: 'pnas.org' },
    ],
  },
];
